--멤버 테이블
CREATE TABLE Mooney_Member(
	MMEM_ID VARCHAR2(30 CHAR) PRIMARY KEY,
	MMEM_PW VARCHAR2(60 CHAR) NOT NULL,
	MMEM_PPHOTO VARCHAR2(500 CHAR), -- 이미지 경로로 충분히 넉넉함
	MMEM_NICK VARCHAR2(30 CHAR) NOT NULL UNIQUE, -- 닉네임 중복 방지
	MMEM_BIR DATE NOT NULL,
	MMEM_REGD DATE DEFAULT SYSDATE NOT NULL, -- 자동 가입일 기록
	MMEM_PNT NUMBER(10) DEFAULT 0 CHECK (MMEM_PNT >= 0) -- 음수 방지
);

INSERT INTO VALUES('TTTT', 12345,'')

CREATE SEQUENCE MMEM_SEQ;
DROP  SEQUENCE MMEM_SEQ;

SELECT *
FROM Mooney_Member;

DELETE 
FROM MOONEY_MEMBER
WHERE MMEM_ID = 'Test2User';


--수입/지출 테이블
CREATE TABLE MOONEY_EXPENSE(
	MEXP_ID NUMBER(10) PRIMARY KEY,
	MEXP_DT DATE NOT NULL,
	MEXP_AMT NUMBER(10) NOT NULL,
	MEXP_DEC varchar2(3000 char) NOT NULL,
	MEXP_TYP char(1) check(MEXP_TYP IN ('E', 'I')),
	MEXP_RPT char(1) check(MEXP_RPT IN ('T', 'F')),
	MEXP_RPTD DATE NOT NULL,
	
	CONSTRAINT FK_MMEM_ID FOREIGN KEY (MEXP_MMEM_ID)
		REFERENCES MOONEY_MEMBER (MMEM_ID)
		ON DELETE CASCADE
);

--알림 테이블
CREATE TABLE MOONEY_NOTIFICATION (
    MNOF_ID        NUMBER(10) PRIMARY KEY,               -- 알림 ID
    MNOF_MMEM_ID   VARCHAR2(30 CHAR) NOT NULL,           -- 회원 ID (외래키)
    MNOF_CONTENT   VARCHAR2(1000) NOT NULL,              -- 알림 내용
    MNOF_TYPE      VARCHAR2(20) NOT NULL,                -- 알림 타입 (예: '지출', '수입', '공지')
    MNOF_DT        DATE DEFAULT SYSDATE NOT NULL,        -- 생성 일시
    MNOF_READ_YN   CHAR(1) DEFAULT 'N' CHECK (MNOF_READ_YN IN ('Y', 'N')),  -- 읽음 여부

    CONSTRAINT FK_MNOF_MEMBER FOREIGN KEY (MNOF_MMEM_ID)
        REFERENCES MOONEY_MEMBER (MMEM_ID)
        ON DELETE CASCADE
);

--수입/지출 카테고리 테이블
CREATE TABLE MOONEY_CATEGORY(
	MCAT_ID NUMBER(10) PRIMARY KEY,
	MCAT_NAME varchar2(30 char) NOT NULL,
	MCAT_COLOR varchar2(10 char) NOT NULL
);
--일기장 테이블
CREATE TABLE MOONEY_Diary(
	MDIA_ID NUMBER(10) PRIMARY KEY,
	MDIA_MMEM_ID varchar2(30 char) NOT NULL,
	MDIA_DATE DATE NOT NULL,
	MDIA_CONTENT varchar2(3000 char) NOT NULL,
	
	CONSTRAINT FK_MDIA_MEMBER FOREIGN KEY (MDIA_MMEM_ID)
		REFERENCES MOONEY_MEMBER (MMEM_ID)
		ON DELETE CASCADE
);

--가계부소비 챌린지
CREATE TABLE MOONEY_CHALLENGE (
    MCHL_ID              NUMBER(10) PRIMARY KEY,              -- 챌린지 ID
    MCHL_MMEM_ID         VARCHAR2(30 CHAR) NOT NULL,          -- 회원 ID (FK)
    MCHL_NAME            VARCHAR2(100) NOT NULL,              -- 챌린지 이름
    MCHL_TARGET_AMOUNT   NUMBER(10) NOT NULL,                 -- 목표 금액
    MCHL_START_DATE      DATE NOT NULL,                       -- 시작일
    MCHL_END_DATE        DATE NOT NULL,                       -- 종료일
    MCHL_STATUS          VARCHAR2(20) DEFAULT '진행중',       -- 상태
    MCHL_REWARD          NUMBER(10) DEFAULT 0,                -- 보상 포인트 (MMEM_PNT에 연동)
    MCHL_CONTENTS        VARCHAR2(2000),                      -- 상세 설명

    CONSTRAINT FK_MCHL_MEMBER FOREIGN KEY (MCHL_MMEM_ID)
        REFERENCES MOONEY_MEMBER (MMEM_ID)
        ON DELETE CASCADE
);

INSERT INTO Mooney_Expense (
    MEXP_ID, MEXP_MMEM_ID, MEXP_DT, MEXP_AMT, MEXP_DEC,
    MEXP_TYPE, MEXP_RPT, MEXP_RPTDD, MEXP_FREQUENCY, MEXP_STATUS
) VALUES (
    10001, 'hihihi234', TO_DATE('2025-07-14', 'YYYY-MM-DD'), 18000, '점심 식사',
    'E', 'F', NULL, 'ONE_TIME', 'COMPLETED'
);

DESCRIBE Mooney_Expense;

SELECT *
FROM Mooney_expense;

DELETE FROM MOONEY_EXPENSE 
WHERE MEXP_ID = 10001;