--멤버 테이블
CREATE TABLE Mooney_Member(
	MMEM_ID VARCHAR2(30 CHAR) PRIMARY KEY,
	MMEM_PW VARCHAR2(60 CHAR) NOT NULL,
	MMEM_PPHOTO VARCHAR2(500 CHAR), -- 이미지 경로로 충분히 넉넉함
	MMEM_NICK VARCHAR2(30 CHAR) NOT NULL UNIQUE, -- 닉네임 중복 방지
	MMEM_BIR DATE NOT NULL,
	MMEM_REGD DATE DEFAULT SYSDATE NOT NULL, -- 자동 가입일 기록
	MMEM_PNT NUMBER(10) DEFAULT 0 CHECK (MMEM_PNT >= 0) -- 음수 방지
);

CREATE SEQUENCE MMEM_SEQ;
DROP  SEQUENCE MMEM_SEQ;

SELECT *
FROM Mooney_Member;

DELETE 
FROM MOONEY_MEMBER
WHERE MMEM_ID = 'hhh234';
SELECT
				TO_CHAR(TRUNC(SYSDATE, 'MM'), 'YYYY-MM-DD')
				|| ' ~ ' ||
				TO_CHAR(LAST_DAY(SYSDATE), 'YYYY-MM-DD') AS 월간범위,
				TO_CHAR(MEXP_DT, 'YYYY-MM-DD') AS 지출일,
				MEXP_DEC AS 지출카테고리,
				MEXP_AMT AS 지출가격
			FROM Mooney_Expense
			WHERE MEXP_MMEM_ID = 'hhhh234'
				AND MEXP_DT BETWEEN TRUNC(SYSDATE, 'MM')
				AND ME
				AND LAST_DAY(SYSDATE) + (23/24) + (59/1440) + (59/86400)
			ORDER BY MEXP_DT;

--수입/지출 테이블
CREATE TABLE MOONEY_EXPENSE(
	MEXP_ID NUMBER(10) PRIMARY KEY,
	MEXP_DT DATE NOT NULL,
	MEXP_AMT NUMBER(10) NOT NULL,
	MEXP_DEC varchar2(3000 char) NOT NULL,
	MEXP_TYP char(1) check(MEXP_TYP IN ('E', 'I')),
	MEXP_RPT char(1) check(MEXP_RPT IN ('T', 'F')),
	MEXP_RPTD DATE NOT NULL,
	
	CONSTRAINT FK_MMEM_ID FOREIGN KEY (MEXP_MMEM_ID)
		REFERENCES MOONEY_MEMBER (MMEM_ID)
		ON DELETE CASCADE
);

	SELECT MEXP_AMT AS 급여,
			       MEXP_DEC AS 금액분류,
			       MEXP_DT AS 급여지급일,
			       MEXP_RPTDD AS 다음급여일
			FROM MOONEY_EXPENSE
			WHERE MEXP_TYPE = 'I'
			  AND MEXP_RPT = 'T'
			  AND MEXP_MMEM_ID = 'hhhh234';

--알림 테이블
CREATE TABLE MOONEY_NOTIFICATION (
    MNOF_ID        NUMBER(10) PRIMARY KEY,               -- 알림 ID
    MNOF_MMEM_ID   VARCHAR2(30 CHAR) NOT NULL,           -- 회원 ID (외래키)
    MNOF_CONTENT   VARCHAR2(1000) NOT NULL,              -- 알림 내용
    MNOF_TYPE      VARCHAR2(20) NOT NULL,                -- 알림 타입 (예: '지출', '수입', '공지')
    MNOF_DT        DATE DEFAULT SYSDATE NOT NULL,        -- 생성 일시
    MNOF_READ_YN   CHAR(1) DEFAULT 'N' CHECK (MNOF_READ_YN IN ('Y', 'N')),  -- 읽음 여부

    CONSTRAINT FK_MNOF_MEMBER FOREIGN KEY (MNOF_MMEM_ID)
        REFERENCES MOONEY_MEMBER (MMEM_ID)
        ON DELETE CASCADE
);

--수입/지출 카테고리 테이블
CREATE TABLE MOONEY_CATEGORY(
	MCAT_ID NUMBER(10) PRIMARY KEY,
	MCAT_NAME varchar2(30 char) NOT NULL,
	MCAT_COLOR varchar2(10 char) NOT NULL
);
--일기장 테이블
CREATE TABLE MOONEY_Diary(
	MDIA_ID NUMBER(10) PRIMARY KEY,
	MDIA_MMEM_ID varchar2(30 char) NOT NULL,
	MDIA_DATE DATE NOT NULL,
	MDIA_CONTENT varchar2(3000 char) NOT NULL,
	
	CONSTRAINT FK_MDIA_MEMBER FOREIGN KEY (MDIA_MMEM_ID)
		REFERENCES MOONEY_MEMBER (MMEM_ID)
		ON DELETE CASCADE
);

--가계부소비 챌린지
CREATE TABLE MOONEY_CHALLENGE (
    MCHL_ID              NUMBER(10) PRIMARY KEY,              -- 챌린지 ID
    MCHL_MMEM_ID         VARCHAR2(30 CHAR) NOT NULL,          -- 회원 ID (FK)
    MCHL_NAME            VARCHAR2(100) NOT NULL,              -- 챌린지 이름
    MCHL_TARGET_AMOUNT   NUMBER(10) NOT NULL,                 -- 목표 금액
    MCHL_START_DATE      DATE NOT NULL,                       -- 시작일
    MCHL_END_DATE        DATE NOT NULL,                       -- 종료일
    MCHL_STATUS          VARCHAR2(20) DEFAULT '진행중',       -- 상태
    MCHL_REWARD          NUMBER(10) DEFAULT 0,                -- 보상 포인트 (MMEM_PNT에 연동)
    MCHL_CONTENTS        VARCHAR2(2000),                      -- 상세 설명

    CONSTRAINT FK_MCHL_MEMBER FOREIGN KEY (MCHL_MMEM_ID)
        REFERENCES MOONEY_MEMBER (MMEM_ID)
        ON DELETE CASCADE
);


SELECT *
FROM MOONEY_EXPENSE;

INSERT INTO MOONEY_EXPENSE VALUES (512242, 'hhhh234', TO_DATE('2025-07-05', 'YYYY-MM-DD'),3500000, '급여',
	'I', 'T', TO_DATE('2025-08-05', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY'
);

SELECT MEXP_AMT AS 급여, MEXP_DEC AS 금액분류, MEXP_DT AS 급여지급일, MEXP_RPTDD AS 다음급여일
FROM MOONEY_EXPENSE
WHERE MEXP_TYPE = 'I' AND MEXP_RPT = 'T' AND MEXP_MMEM_ID = 'hhhh234'

SELECT MEXP_AMT AS 사용금액, 
       MEXP_DEC AS 사용처, 
       MEXP_DT AS 지출일
FROM MOONEY_EXPENSE
WHERE MEXP_TYPE = 'E' 
  AND MEXP_MMEM_ID = 'hhhh234'
  AND EXTRACT(YEAR FROM MEXP_DT) = EXTRACT(YEAR FROM SYSDATE)
  AND EXTRACT(MONTH FROM MEXP_DT) = EXTRACT(MONTH FROM SYSDATE);

SELECT 
       MEXP_AMT AS 사용금액, 
       MEXP_DEC AS 사용처, 
       MEXP_DT AS 지출일,
       TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'), 'YYYY-MM-DD') || ' ~ ' || 
       TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE, -1)), 'YYYY-MM-DD') AS 월간범위
FROM MOONEY_EXPENSE
WHERE MEXP_TYPE = 'E' 
  AND MEXP_MMEM_ID = 'hhhh234'
  AND EXTRACT(YEAR FROM MEXP_DT) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -1))
  AND EXTRACT(MONTH FROM MEXP_DT) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1));


SELECT MEXP_DEC, MEXP_DT
FROM MOONEY_EXPENSE
WHERE MEXP_TYPE='E' AND MEXP_MMEM_ID = 'hhhh234';

DELETE
FROM Mooney_Expense
WHERE MEXP_DEC = '편의점 삼각김밥, 컵라면'

INSERT ALL
  INTO Mooney_Expense (MEXP_ID, MEXP_MMEM_ID, MEXP_DT, MEXP_AMT, MEXP_DEC,
    MEXP_TYPE, MEXP_RPT, MEXP_RPTDD, MEXP_STATUS, MEXP_FREQUENCY)
  VALUES (170, 'hhhh234', TO_DATE('2025-06-01', 'YYYY-MM-DD'), 6800, '카페 아메리카노/크루아상', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (171, 'hhhh234', TO_DATE('2025-06-02', 'YYYY-MM-DD'), 8200, '일식집 규동/된장국', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (172, 'hhhh234', TO_DATE('2025-06-03', 'YYYY-MM-DD'), 11900, '넷플릭스 구독 월 이용료', 'E', 'T', TO_DATE('2025-07-03', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (173, 'hhhh234', TO_DATE('2025-06-04', 'YYYY-MM-DD'), 5400, '편의점 김밥/아이스티', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (174, 'hhhh234', TO_DATE('2025-06-05', 'YYYY-MM-DD'), 9500, '치킨 윙봉/피클', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (175, 'hhhh234', TO_DATE('2025-06-06', 'YYYY-MM-DD'), 3800, '편의점 우유/쿠키', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (176, 'hhhh234', TO_DATE('2025-06-07', 'YYYY-MM-DD'), 8900, '스포티파이 프리미엄 구독', 'E', 'T', TO_DATE('2025-07-07', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (177, 'hhhh234', TO_DATE('2025-06-08', 'YYYY-MM-DD'), 7200, '버거킹 와퍼 세트', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (178, 'hhhh234', TO_DATE('2025-06-09', 'YYYY-MM-DD'), 4700, '편의점 라면/콜라', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (179, 'hhhh234', TO_DATE('2025-06-10', 'YYYY-MM-DD'), 12900, '휴대폰 통신비 요금', 'E', 'T', TO_DATE('2025-07-10', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (180, 'hhhh234', TO_DATE('2025-06-11', 'YYYY-MM-DD'), 6300, '스타벅스 프라푸치노', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (181, 'hhhh234', TO_DATE('2025-06-12', 'YYYY-MM-DD'), 8700, '한식집 김치찜/공기밥', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (182, 'hhhh234', TO_DATE('2025-06-13', 'YYYY-MM-DD'), 5200, '편의점 도시락/요구르트', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (183, 'hhhh234', TO_DATE('2025-06-14', 'YYYY-MM-DD'), 12400, '피자 라지 1판 (페퍼로니)', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (184, 'hhhh234', TO_DATE('2025-06-15', 'YYYY-MM-DD'), 4900, '파리바게뜨 빵/커피', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (185, 'hhhh234', TO_DATE('2025-06-16', 'YYYY-MM-DD'), 7800, '족발보쌈 소짜 1인분', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (186, 'hhhh234', TO_DATE('2025-06-17', 'YYYY-MM-DD'), 5600, '편의점 삼각김밥 2개/녹차', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (187, 'hhhh234', TO_DATE('2025-06-18', 'YYYY-MM-DD'), 15600, '노래방 2시간 이용료', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (188, 'hhhh234', TO_DATE('2025-06-19', 'YYYY-MM-DD'), 6100, '투썸플레이스 케이크/차', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (189, 'hhhh234', TO_DATE('2025-06-20', 'YYYY-MM-DD'), 9200, '마라탕 곱빼기', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (190, 'hhhh234', TO_DATE('2025-06-21', 'YYYY-MM-DD'), 3900, '편의점 아이스크림/음료', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (191, 'hhhh234', TO_DATE('2025-06-22', 'YYYY-MM-DD'), 12900, '인터넷 요금', 'E', 'T', TO_DATE('2025-07-22', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (192, 'hhhh234', TO_DATE('2025-06-23', 'YYYY-MM-DD'), 7400, '맥도날드 빅맥 세트', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (193, 'hhhh234', TO_DATE('2025-06-24', 'YYYY-MM-DD'), 5800, '떡볶이 순대 세트', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (194, 'hhhh234', TO_DATE('2025-06-25', 'YYYY-MM-DD'), 4300, '편의점 샐러드/물', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (195, 'hhhh234', TO_DATE('2025-06-26', 'YYYY-MM-DD'), 8600, '갈비탕 1인분', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (196, 'hhhh234', TO_DATE('2025-06-27', 'YYYY-MM-DD'), 6500, '초밥 세트 8피스', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (197, 'hhhh234', TO_DATE('2025-06-28', 'YYYY-MM-DD'), 7900, '쌀국수/베트남 롤', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (198, 'hhhh234', TO_DATE('2025-06-29', 'YYYY-MM-DD'), 4600, '편의점 과자/에이드', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (199, 'hhhh234', TO_DATE('2025-06-30', 'YYYY-MM-DD'), 11200, '서점 소설책 2권', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
SELECT * FROM dual;

INSERT INTO MOONEY_EXPENSE VALUES(88887, 'hhhh234', TO_DATE('2025-07-02', 'YYYY-MM-DD'), 180000, '파인 다이닝바 저녁식사', 'E', 'F', NULL, 'COMPLETED', 'DAILY');

INSERT ALL
  INTO Mooney_Expense (MEXP_ID, MEXP_MMEM_ID, MEXP_DT, MEXP_AMT, MEXP_DEC,
    MEXP_TYPE, MEXP_RPT, MEXP_RPTDD, MEXP_STATUS, MEXP_FREQUENCY)
  VALUES (200, 'hhhh234', TO_DATE('2025-07-01', 'YYYY-MM-DD'), 5300, '편의점 바나나우유/샌드위치', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (201, 'hhhh234', TO_DATE('2025-07-02', 'YYYY-MM-DD'), 4700, '분식집 떡볶이/순대', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (202, 'hhhh234', TO_DATE('2025-07-03', 'YYYY-MM-DD'), 11900, '넷플릭스 구독 월 이용료', 'E', 'T', TO_DATE('2025-08-03', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (203, 'hhhh234', TO_DATE('2025-07-04', 'YYYY-MM-DD'), 5800, '도시락 배달/아이스 아메리카노', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (204, 'hhhh234', TO_DATE('2025-07-05', 'YYYY-MM-DD'), 7100, '제육덮밥 세트 메뉴', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (205, 'hhhh234', TO_DATE('2025-07-06', 'YYYY-MM-DD'), 4600, '편의점 컵라면/콜라', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (206, 'hhhh234', TO_DATE('2025-07-07', 'YYYY-MM-DD'), 8900, '스포티파이 프리미엄 구독', 'E', 'T', TO_DATE('2025-08-07', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (207, 'hhhh234', TO_DATE('2025-07-08', 'YYYY-MM-DD'), 6100, '샐러드 도시락/생수', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (208, 'hhhh234', TO_DATE('2025-07-09', 'YYYY-MM-DD'), 5600, '편의점 샌드위치/에너지드링크', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (209, 'hhhh234', TO_DATE('2025-07-10', 'YYYY-MM-DD'), 12900, '휴대폰 통신비 요금', 'E', 'T', TO_DATE('2025-08-10', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (210, 'hhhh234', TO_DATE('2025-07-11', 'YYYY-MM-DD'), 4900, '커피 전문점 아메리카노', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (211, 'hhhh234', TO_DATE('2025-07-12', 'YYYY-MM-DD'), 7400, '돈까스 정식 세트', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (212, 'hhhh234', TO_DATE('2025-07-13', 'YYYY-MM-DD'), 4600, '편의점 삼각김밥/탄산음료', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (213, 'hhhh234', TO_DATE('2025-07-14', 'YYYY-MM-DD'), 7800, '중식당 짜장면/탕수육 소', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (214, 'hhhh234', TO_DATE('2025-07-15', 'YYYY-MM-DD'), 5900, '볶음밥/아이스티', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (215, 'hhhh234', TO_DATE('2025-07-16', 'YYYY-MM-DD'), 6300, '비빔밥/된장국', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (216, 'hhhh234', TO_DATE('2025-07-17', 'YYYY-MM-DD'), 5000, '편의점 샌드위치/커피', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (217, 'hhhh234', TO_DATE('2025-07-18', 'YYYY-MM-DD'), 10200, '영화관 관람 (일반 1인)', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (218, 'hhhh234', TO_DATE('2025-07-19', 'YYYY-MM-DD'), 5300, '커피/쿠키', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (219, 'hhhh234', TO_DATE('2025-07-20', 'YYYY-MM-DD'), 7000, '김치찌개 정식', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (220, 'hhhh234', TO_DATE('2025-07-21', 'YYYY-MM-DD'), 4500, '편의점 컵라면/음료', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (221, 'hhhh234', TO_DATE('2025-07-22', 'YYYY-MM-DD'), 12900, '인터넷 요금', 'E', 'T', TO_DATE('2025-08-22', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY')
  INTO Mooney_Expense VALUES (222, 'hhhh234', TO_DATE('2025-07-23', 'YYYY-MM-DD'), 4800, '커피/과자', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (223, 'hhhh234', TO_DATE('2025-07-24', 'YYYY-MM-DD'), 7300, '제육볶음 정식', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (224, 'hhhh234', TO_DATE('2025-07-25', 'YYYY-MM-DD'), 4500, '편의점 도시락', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (225, 'hhhh234', TO_DATE('2025-07-26', 'YYYY-MM-DD'), 5400, '베이커리 샌드위치/커피', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (226, 'hhhh234', TO_DATE('2025-07-27', 'YYYY-MM-DD'), 5700, '볶음밥/음료수', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (227, 'hhhh234', TO_DATE('2025-07-28', 'YYYY-MM-DD'), 6200, '냉면/만두', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (228, 'hhhh234', TO_DATE('2025-07-29', 'YYYY-MM-DD'), 4900, '편의점 삼각김밥/주스', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
  INTO Mooney_Expense VALUES (229, 'hhhh234', TO_DATE('2025-07-30', 'YYYY-MM-DD'), 6200, '서점 도서 구매 (자기계발서 1권)', 'E', 'F', NULL, 'COMPLETED', 'DAILY')
SELECT * FROM dual;


SELECT SUM(COUNT(MEXP_DEC)) AS CNT
FROM MOONEY_EXPENSE
WHERE MEXP_MMEM_ID = 'hhhh234'
  AND MEXP_TYPE = 'E'
  AND EXTRACT(MONTH FROM MEXP_DT) =  EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1))
GROUP BY MEXP_DEC
ORDER BY CNT DESC;


SELECT SUM(COUNT(MEXP_DEC)) AS CNT, SUM(MEXP_AMT)
FROM MOONEY_EXPENSE
WHERE MEXP_MMEM_ID = 'hhhh234'
  AND MEXP_TYPE = 'E'
  AND EXTRACT(MONTH FROM MEXP_DT) =  EXTRACT(MONTH FROM SYSDATE)
GROUP BY MEXP_DEC
ORDER BY CNT DESC;

DELETE FROM 
MOONEY_EXPENSE 
WHERE MEXP_MMEM_ID = 'hhhh234'

SELECT 
    MEXP_DEC AS 지출내용,
    COUNT(*) AS 발생횟수,
    SUM(MEXP_AMT) AS 총금액
FROM MOONEY_EXPENSE
WHERE MEXP_MMEM_ID = 'hhhh234'
  AND MEXP_TYPE = 'E'
  AND EXTRACT(MONTH FROM MEXP_DT) = EXTRACT(MONTH FROM SYSDATE)
  AND MEXP_AMT >= 100000  -- 또는 500000
GROUP BY MEXP_DEC
ORDER BY 총금액 DESC;

SELECT *
FROM Mooney_expense;

SELECT
			    MEXP_DEC AS 지출내용,
			    COUNT(*) AS 발생횟수,
			    SUM(MEXP_AMT) AS 총금액
			FROM MOONEY_EXPENSE
			WHERE MEXP_MMEM_ID = 'hhhh234'
			  AND MEXP_TYPE = 'E'
			  AND EXTRACT(MONTH FROM MEXP_DT) = EXTRACT(MONTH FROM SYSDATE)
			  AND MEXP_AMT >= 100000  -- 또는 500000
			GROUP BY MEXP_DEC
			ORDER BY 총금액 DESC
			
UPDATE MOONEY_EXPENSE
SET MEXP_DEC = '부모님 용돈', MEXP_AMT = 1000000, MEXP_FREQUENCY = 'MONTHLY'
WHERE MEXP_RPT = 'T' AND MEXP_Dt = TO_DATE('2025-07-30', 'YYYY-MM-DD');

-- 지난달 총 지출
SELECT SUM(MEXP_AMT) 
FROM Mooney_Expense 
WHERE MEXP_MMEM_ID = 'hhhh234'
  AND MEXP_DT BETWEEN TO_DATE('2025-06-01', 'YYYY-MM-DD') AND TO_DATE('2025-06-30', 'YYYY-MM-DD');

-- 이번달 총 지출
SELECT SUM(MEXP_AMT) 
FROM Mooney_Expense 
WHERE MEXP_MMEM_ID = 'hhhh234'
  AND MEXP_DT BETWEEN TO_DATE('2025-07-01', 'YYYY-MM-DD') AND SYSDATE;
513513	hhhh234	2025-06-05 00:00:00.000	3500000	급여	I	T	2025-07-05 00:00:00.000	COMPLETED	MONTHLY	12

INSERT INTO MOONEY_EXPENSE VALUES(513514, 'hhhh234', TO_DATE('2025-07-05', 'YYYY-MM-DD'), 3500000, '급여', 'I', 'T', TO_DATE('2025-08-05', 'YYYY-MM-DD'), 'COMPLETED', 'MONTHLY', 12);
SELECT *
FROM MOONEY_EXPENSE;

SELECT
TO_CHAR(TRUNC(SYSDATE, 'MM'), 'YYYY-MM-DD')
|| ' ~ ' ||
TO_CHAR(LAST_DAY(SYSDATE), 'YYYY-MM-DD') AS 월간범위,
TO_CHAR(MEXP_DT, 'YYYY-MM-DD') AS 지출일,
	MEXP_DEC AS 지출카테고리,
	MEXP_AMT AS 지출가격
FROM Mooney_Expense
WHERE MEXP_MMEM_ID = 'hhhh234'
	AND MEXP_TYPE = 'E'
AND MEXP_DT BETWEEN TRUNC(SYSDATE, 'MM')
	AND LAST_DAY(SYSDATE) + (23/24) + (59/1440) + (59/86400)
ORDER BY MEXP_DT;

SELECT MEXP_AMT AS 급여,
			       MEXP_DEC AS 금액분류,
			       MEXP_DT AS 급여지급일,
			       MEXP_RPTDD AS 다음급여일
			FROM MOONEY_EXPENSE
			WHERE MEXP_TYPE = 'I'
			  AND MEXP_RPT = 'T'
			  AND MEXP_MMEM_ID = 'hhhh234'
			  AND EXTRACT(MONTH FROM MEXP_DT) = EXTRACT(MONTH FROM SYSDATE);




